apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv2
spec:
  storageClassName: do-block-storage
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www1"
