apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: wp-prod-issuer1
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: davidochobits@colaboratorio.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
